version: "3.9"

services:
  nginx:
    build: .
    container_name: sip-downdetector-nginx
    ports:
      - "8000:80"
    volumes:
      # наша конфигурация nginx
      - ./nginx/config.conf:/etc/nginx/conf.d/default.conf:ro
      # статика (должна быть writable для log_processor.py)
      - ./nginx/html:/usr/share/nginx/html
      # логи nginx
      - ./logs:/var/log/nginx
      # скрипты для крона
      - ./scripts:/app/scripts:ro
    restart: unless-stopped
